baseURL = "/"
languageCode = "en-us"
title = "Ken Gorab"
theme = "hello-friend"

[markup.goldmark.renderer]
unsafe= true

[languages]

[languages.en]
title = "Ken Gorab"
subtitle = ""
keywords = "senior software engineer nyc programming java javascript typescript react golang ruby rust"
copyright = ""
dateFormatSingle = "Jan 2, 2006"
dateFormatList = "Jan 2, 2006"

[languages.en.params.logo]
logoText = "~ken.gorab"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
weight = 1
name = "About"
url = "/me"

[[languages.en.menu.main]]
identifier = "posts"
weight = 2
name = "Posts"
url = "/"

[[languages.en.menu.main]]
identifier = "github"
weight = 3
name = "Github"
url = "https://github.com/kengorab"

[[languages.en.menu.main]]
identifier = "resume"
weight = 4
name = "Resume"
url = "/resume.pdf"
